### ISSUE TITLE
unable to use v2 with awaitApply and additional inputs

### ISSUE THREAD

**Issue by ghost** [addresscloud/terraform-cloud-action#16]
When trying ot use the following 

```
      - name: Terraform Cloud
        uses: addresscloud/terraform-cloud-action@v1.0.0
        with:
          tfToken: ${{ secrets.TERRAFORM_TOKEN }}
          tfOrg: '<ORG>'
          tfWorkspace: '<WORKSPACE>'
          filePath: './build.tar.gz'
          identifier: ${{ github.sha }}
          awaitApply: true
          awaitInterval: 60
          retryLimit: 5
```

I get the following error
`Unexpected input(s) 'awaitApply', 'awaitInterval', 'retryLimit', valid inputs are ['tfToken', 'tfOrg', 'tfWorkspace', 'filePath', 'identifier']`

When attempting to use 

```
      - name: Terraform Cloud
        uses: addresscloud/terraform-cloud-action@v2.0.0
        with:
          tfToken: ${{ secrets.TERRAFORM_TOKEN }}
          tfOrg: '<ORG>'
          tfWorkspace: '<WORKSPACE>'
          filePath: './build.tar.gz'
          identifier: ${{ github.sha }}
          awaitApply: true
          awaitInterval: 60
          retryLimit: 5
```

I get the following error

`Error checking the workspace: Request failed with status code 401`

I'm assuming this is because the version 2 release has not been created and uploaded to the github action marketplace. 

@tomasholderness is this possible to be done, this looks like a really useful action
